### ISSUE TITLE
delhome not working

### ISSUE THREAD

**Issue by deathjHK** [fuzeblocks/HomePlugin#2]
As the title says, /delhome isn't doing anything - not even logwise

**Comment by fuzeblocks** [comment]
> As the title says, /delhome isn't doing anything - not even logwise

Hi, thanks for letting me know, I'll do a fix very soon So be present!

Thanks for using the plugin and opening an issue

**Comment by fuzeblocks** [comment]
First of all, do you have an error? Could you describe your manipulation to me?Mercier

**Comment by fuzeblocks** [comment]
First of all, do you have an error? Could you describe your manipulation to me?
THANKS

**Comment by fuzeblocks** [comment]
First of all, do you have an error? Could you describe your manipulation to me?
THANKS

**Comment by deathjHK** [comment]
Sadly there's no error message or anything like that being output to the logs. Everything is at default settings, except for some of the language which I swapped in the config file to have an english theme going on. /delhome doesn't seems to have any effect, neither as default rank nor as operator

**Comment by fuzeblocks** [comment]
Ok ok thank you

**Comment by fuzeblocks** [comment]
Ok ok thank you

**Comment by deathjHK** [comment]
Is there any verbose/debug option I can toggle, so the plugin outputs everything to the log?

**Comment by fuzeblocks** [comment]
No, this feature has not yet been implemented. But you can describe the command to me with the arguments as well as the homes.yml file

**Comment by fuzeblocks** [comment]
No, this feature has not yet been implemented. But you can describe the command to me with the arguments as well as the homes.yml file

**Comment by deathjHK** [comment]
For example: "/delhome bed" is expected to delete the home "bed" from me, but it doesn't

I have censored the UUIDs, but they're correct in the original File
<details>

<summary>homes.yml</summary>

####################################:     //(My homes)
  Home:
    home:
      X: -3128.9055865929668
      Y: 121.0
      Z: 2076.2969686754427
      PITCH: 9.107629
      YAW: 4.185791
      World: world
    bed:
      X: -3120.980404832079
      Y: 125.0
      Z: 2081.135373178697
      PITCH: 26.931404
      YAW: -82.9837
      World: world
    Fortress:
      X: -248.2204973186087
      Y: 59.0
      Z: -133.33442132935002
      PITCH: 14.890035
      YAW: -88.8302
      World: world_nether
    Hafen:
      X: -3221.299266711785
      Y: 68.0
      Z: 2315.5370299072756
      PITCH: 21.685684
      YAW: 155.15283
      World: world
    xp:
      X: -3043.093519691015
      Y: 87.0
      Z: 1997.4400990419156
      PITCH: 36.230736
      YAW: -91.37915
      World: world
    creeper:
      X: -2848.6897249281024
      Y: 251.0
      Z: 3824.555244670836
      PITCH: 14.353815
      YAW: -169.758
      World: world
####################################:
  Home:
    ej:
      X: -3152.4941290933407
      Y: 117.0
      Z: 2060.9574680852693
      PITCH: 10.350007
      YAW: 16.799316
      World: world
####################################:
  Home:
    e:
      X: -3129.148257507388
      Y: 120.0
      Z: 2064.8818865322096
      PITCH: 10.047617
      YAW: 1.3596191
      World: world
    end:
      X: -241.61357685516893
      Y: 63.0
      Z: 1316.5133795449522
      PITCH: 24.899248
      YAW: 1.0515765
      World: world_the_end
####################################:
  Home:
    Eric:
      X: -3143.292301657074
      Y: 117.0
      Z: 2044.9346678309948
      PITCH: 9.600046
      YAW: -107.98755
      World: world
    Majuicy:
      X: -3264.1178690909005
      Y: 64.0
      Z: 2035.9303247510884
      PITCH: 20.999914
      YAW: 74.56357
      World: world
####################################:
  Home:
    lager:
      X: -3128.7278131397165
      Y: 120.5
      Z: 2076.3231761600855
      PITCH: 12.300008
      YAW: -6.7526026
      World: world


</details>

**Comment by deathjHK** [comment]
If I use MYSQL instead of YAML the plugin just crashes at startup and I get an error printed in log, tried both with Redis on and off
Mind that I'm on Spigot 1.21, but the plugin has had the same issue on Spigot 1.20.6, so it probably can't be an issue with the Spigot version

<details>

<summary>Error from log</summary>

15.06 11:27:36 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
15.06 11:27:36 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4198-Spigot-146439e-0a0229b]
15.06 11:27:36 [Server] INFO at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4198-Spigot-146439e-0a0229b]
15.06 11:27:36 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:237) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4198-Spigot-146439e-0a0229b]
15.06 11:27:36 [Server] INFO at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4198-Spigot-146439e-0a0229b]
15.06 11:27:36 [Server] INFO at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4198-Spigot-146439e-0a0229b]
15.06 11:27:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
15.06 11:27:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
15.06 11:27:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
15.06 11:27:36 [Server] INFO at fr.fuzeblocks.homeplugin.HomePlugin.onEnable(HomePlugin.java:49) ~[?:?]
15.06 11:27:36 [Server] INFO at fr.fuzeblocks.homeplugin.HomePlugin.databaseRegistration(HomePlugin.java:98) ~[?:?]
15.06 11:27:36 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
15.06 11:27:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
15.06 11:27:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:117) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
15.06 11:27:36 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
15.06 11:27:36 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:172) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
15.06 11:27:36 [Server] INFO at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
15.06 11:27:36 [Server] INFO at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
15.06 11:27:36 [Server] INFO at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
15.06 11:27:36 [Server] INFO at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
15.06 11:27:36 [Server] INFO java.lang.IllegalStateException: zip file closed
15.06 11:27:36 [Server] Server thread/ERROR Error occurred while enabling HomePlugin v0.6.3 (Is it up to date?)
15.06 11:27:36 [Server] Server thread/INFO [HomePlugin] Registering Manager
15.06 11:27:36 [Server] Server thread/INFO [HomePlugin] ------------------------------------------------------
15.06 11:27:36 [Server] Server thread/INFO [HomePlugin] ----------HomePlugin a Ã©tÃ© Ã©teint avec succÃ©s !----------
15.06 11:27:36 [Server] Server thread/INFO [HomePlugin] ----------------------HomePlugin----------------------
15.06 11:27:36 [Server] Server thread/INFO [HomePlugin] Disabling HomePlugin v0.6.3
15.06 11:27:36 [Server] Server thread/WARN Error when connecting to DB ! Exiting...
15.06 11:27:32 [Server] Server thread/INFO DatabaseCredentials
15.06 11:27:32 [Server] Server thread/INFO Config.Connector.
15.06 11:27:32 [Server] Server thread/INFO [HomePlugin] Registering Database
15.06 11:27:32 [Server] Server thread/INFO [HomePlugin] Redis registered successfully !
15.06 11:27:31 [Server] Server thread/INFO [HomePlugin] MYSQL has been selected !
15.06 11:27:31 [Server] Server thread/INFO [HomePlugin] Enabling HomePlugin v0.6.3

</details>

**Comment by fuzeblocks** [comment]
Thank you very much for the details, I will correct the errors as soon as possible

**Comment by fuzeblocks** [comment]
Fixed !

**Comment by fuzeblocks** [comment]
Fixed !
